#include "tm4c123gh6pm.h"
#include "PLL.h"

void PLL_Init(void){
	SYSCTL_RCC2_R |= SYSCTL_RCC2_USERCC2;
	SYSCTL_RCC2_R |= SYSCTL_RCC2_BYPASS2;
	SYSCTL_RCC_R &= ~SYSCTL_RCC_XTAL_M;
	SYSCTL_RCC_R |= SYSCTL_RCC_XTAL_16MHZ;
	SYSCTL_RCC2_R &= ~SYSCTL_RCC2_OSCSRC2_M;
	SYSCTL_RCC2_R |= SYSCTL_RCC2_OSCSRC2_MO;
	SYSCTL_RCC2_R &= ~SYSCTL_RCC2_PWRDN2;
	SYSCTL_RCC2_R |= SYSCTL_RCC2_DIV400;
	SYSCTL_RCC2_R = (SYSCTL_RCC2_R&~0x1FC00000) | (SYSDIV2<<22);
	while((SYSCTL_RIS_R&SYSCTL_RIS_PLLLRIS)==0){};
	SYSCTL_RCC2_R &= ~SYSCTL_RCC2_BYPASS2;
}
